### ISSUE TITLE
metrics表的问题

### ISSUE THREAD

**Issue by KouenSoftWare** [didi/kafka-manager#13]
想问下，指标数据存在mysql里面，每天数据量是topic*1440，这个数据量有点大，如果myslq超过千万以后，就会很卡，请问后续再这方便有优化方案吗

**Comment by ZQKC** [comment]
确实数据量会很大，后续大致会有两个方式进行优化，1.MySQL上优化数据量；2.支持时序数据库。

1、MySQL上优化数据量
增加动态变更采样周期、自动删除历史数据、对无效流量数据进行过滤等功能来减少数据量。

2、支持时序数据库来存储数据

不知道你这边是否有更好的方案一起交流一下。

**Comment by ZQKC** [comment]
和 https://github.com/didi/kafka-manager/issues/68 该issure重复，关闭当前issure，后续考虑接入类似tsdb进行存储监控数据
