### ISSUE TITLE
执行到create_mysql_table.sql到阿里云的mysql 报错

### ISSUE THREAD

**Issue by sunyaf** [didi/kafka-manager#14]
CREATE TABLE `topic_favorite`
CREATE TABLE `account`
创建上面两张表报错
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes

**Comment by ZQKC** [comment]
你的MySQL版本是？？MySQL 5.6及以前的版本，使用InnoDB表时会有这个问题。
临时解决是修改sql，将key的长度缩短一些。
后续我理一下我们sql的key的长度，如果可以则尽量不超过这个限制。

**Comment by killinitzero** [comment]
mysql 5.7 也发生一样报错
ERROR 1071 (42000) at line 166: Specified key was too long; max key length is 767 bytes

**Comment by ZQKC** [comment]
> mysql 5.7 也发生一样报错 ERROR 1071 (42000) at line 166: Specified key was too long; max key length is 767 bytes

可以看一下FAQ
