### ISSUE TITLE
get metrics fail

### ISSUE THREAD

**Issue by LuckyMango** [didi/kafka-manager#19]
Kafka版本：2.1.0
Zookeeper版本：3.5.5
 #JMX端口连接成功，项目会一直循环报错getSpecifiedBrokerMetricsFromJmx@JmxServiceImpl, get metrics fail, objectName:kafka.network:type=RequestMetrics,name=RequestsPerSec,request=FetchConsumer.

![image](https://user-images.githubusercontent.com/43702671/82877039-49b36780-9f6c-11ea-8c69-40f9e4a99eb1.png)
![image](https://user-images.githubusercontent.com/43702671/82876975-2a1c3f00-9f6c-11ea-9bce-a141f9ac0051.png)

**Comment by ZQKC** [comment]
Broker的JMX上有这个指标么？？

**Comment by LuckyMango** [comment]
> Broker的JMX上有这个指标么？？

 jconsole 查看也有这个指标
