### ISSUE TITLE
Does it provide good compilation

### ISSUE THREAD

**Issue by llnbe** [didi/kafka-manager#2]
Does it provide good compilation

**Comment by ZQKC** [comment]
what's the problem have you meet? 
latest days, we have fixed some compilation problems

**Comment by llnbe** [comment]
Not yet
Suggest adding email based alerts.

**Comment by ZQKC** [comment]
Good suggestion,  later we see how to integrate.
Another, we will integrate [nightingales](https://github.com/didi/nightingale).
