### ISSUE TITLE
java.rmi.ConnectException: Connection refused to host: 127.0.0.1

### ISSUE THREAD

**Issue by LuckyMango** [didi/kafka-manager#20]
项目运行一段时间报错，java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is:
JMX端口开启成，jconsole可以获取正常指标。

![image](https://user-images.githubusercontent.com/43702671/83369982-95dd2c80-a3f0-11ea-87cb-5efe7b823f07.png)

**Comment by LuckyMango** [comment]
出现问题原因：本地环境没有DNS获取机器IP失败，JMX默认连接127.0.0.1.
解决方案：修改kafka-run-class.sh脚本，找到JMX Settings这段
```java
# JMX settings
if [ -z "$KAFKA_JMX_OPTS" ]; then
  KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote -Djava.rmi.server.hostname=本机IP -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false "
fi

```
Djava.rmi.server.hostname  这个参数换为本机IP即可

**Comment by ZQKC** [comment]
👍
如果修改kafka-run-class.sh比较麻烦的话，也可以修改/etc/hosts文件，增加一条 “hostname  实际ip”的映射

**Comment by MargeDog** [comment]
@ZQKC 本地环境DNS获取IP是成功的情况下也报这个错是什么原因呢？部分机器有出现这个问题，dns都是可以解析出来的

**Comment by ZQKC** [comment]
1、提到说部分机器，这块和正常的机器有什么差别么？
2、如果没有结论，入群私聊一下具体的错误信息吧。
