### ISSUE TITLE
希望能添加统计消息总数的功能

### ISSUE THREAD

**Issue by LuckyMango** [didi/kafka-manager#23]
希望官方能添加统计各个集群生产消息的总数和未消费消息的总数，自己根据已有的实现写了个统计各个集群生产消息和未消费消息的总数的功能。但是很遗憾的是，源码里面必须是有客户端进行消费的时候才能看到分区偏移量从而进行统计。如果没有消费者进行消费，也就没办法统计生产消息的总数了。

**Comment by ZQKC** [comment]
具体需求私聊沟通一下吧。展示“未消费消息的总数”的这个需求不是特别合理
