### ISSUE TITLE
这块sasl 怎么配置，还有集群怎么删除， 有方法没有

### ISSUE THREAD

**Issue by llnbe** [didi/kafka-manager#41]
![图片](https://user-images.githubusercontent.com/32897413/87659773-9fe4a000-c790-11ea-8c95-ea245d6efa83.png)

这块sasl 怎么配置，还有集群怎么删除， 有方法没有

**Comment by ZQKC** [comment]
1、SASL的配置，这个可以入群私聊一下。
2、删除集群这个有点不够友好，需要直接操作DB，2.0版本会增加一个删除的按钮。

**Comment by ZQKC** [comment]
1、新版可以直接配置在集群属性里面。
2、新版已经具备删除的能力。
