### ISSUE TITLE
资源审批模块-Topic 申请 审批通过时审核意见为空工单sql 更新会报错，但是topic 却可以创建

### ISSUE THREAD

**Issue by matebase** [didi/kafka-manager#43]
![image](https://user-images.githubusercontent.com/18496797/88132577-7acdb280-cc12-11ea-89eb-3513a66cfbf6.png)
![image](https://user-images.githubusercontent.com/18496797/88132667-bec0b780-cc12-11ea-9700-7e70bdcaa1bd.png)
![image](https://user-images.githubusercontent.com/18496797/88132711-d9932c00-cc12-11ea-9fa5-9166ef9c5267.png)

**Comment by ZQKC** [comment]
多谢，这两天我们修复一下，也欢迎共建提PR。

**Comment by matebase** [comment]
> 多谢，这两天我们修复一下，也欢迎共建提PR。

这两天又发现两个小问题
