### ISSUE TITLE
审核Topic扩容工单报错

### ISSUE THREAD

**Issue by xiaoxinxin85** [didi/kafka-manager#45]
审核Topic扩容工单时，提示“create topic success, but update order status failed, err:without authority to cancel the order”，是什么原因？
![image](https://user-images.githubusercontent.com/24424783/88370243-413ca900-cdc4-11ea-90d4-1e97869f4155.png)

**Comment by xiaoxinxin85** [comment]
页面提示报错，但是分区已经添加成功了。。。

**Comment by ZQKC** [comment]
好的，周末这两天我们修复一下

**Comment by ZQKC** [comment]
DONE
