### ISSUE TITLE
kafka集群有数据写入及消费，manager大部分报表没有数据展示

### ISSUE THREAD

**Issue by lijun535535** [didi/kafka-manager#46]
数据不断写入且消费，分区有偏移量，但消费者组始终无数据，topic历史流量和实时流量始终无数据，broker所有图表无数据展示
![image](https://user-images.githubusercontent.com/31472166/88516042-4184b080-d01f-11ea-977e-19fd082bcba0.png)
![image](https://user-images.githubusercontent.com/31472166/88516107-59f4cb00-d01f-11ea-8cec-eb71b19c554a.png)

**Comment by lijun535535** [comment]
![image](https://user-images.githubusercontent.com/31472166/88516524-fd45e000-d01f-11ea-80d3-93a7efd65a95.png)

**Comment by pierre94** [comment]
jmx开了么

**Comment by camilesing** [comment]
请问JMX的端口参数在`kafka-manager`的哪儿加入进去呢？添加集群的表单中看来并没有这个选项

**Comment by ZQKC** [comment]
JMX端口是在Kafka Broker启动的时候配置的，配置之后，kafka-manager会自动感知到

**Comment by ZQKC** [comment]
滞留过久，无反馈，关闭该ISSURE
