### ISSUE TITLE
执行 mvn install ,console模块报错，不能生成dist目录

### ISSUE THREAD

**Issue by tzpBingo** [didi/kafka-manager#56]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mobx-ts-example@1.0.0 pre-build: `cross-env NODE_ENV=production webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the mobx-ts-example@1.0.0 pre-build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2020-09-22T09_09_03_990Z-debug.log

debug.log:
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\ware\\nodejs\\node.exe',
1 verbose cli   'D:\\ware\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'pre-build' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'pre-build' ]
5 info lifecycle mobx-ts-example@1.0.0~pre-build: mobx-ts-example@1.0.0
6 verbose lifecycle mobx-ts-example@1.0.0~pre-build: unsafe-perm in lifecycle true
7 verbose lifecycle mobx-ts-example@1.0.0~pre-build: PATH: D:\ware\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\me\github\kafka-manager\console\node_modules\.bin;C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.2.2381.0_x64__8wekyb3d8bbwe;D:\ware\SecureCRT\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\WINDOWS\System32\OpenSSH\;D:\ware\TortoiseSVN\bin;D:\ware\PuTTY\;D:\ware\Git\cmd;D:\ware\Calibre\;D:\ware\nodejs\;C:\Program Files (x86)\ZeroTier\One\;D:\ware\Go\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;D:\ware\scala12\bin;D:\ware\UltraEdit;C:\Program Files\IDM Computer Solutions\UltraCompare;D:\ware\Python37\Scripts\;D:\ware\Python37\;D:\ware\Scoop\shims;C:\Users\me\AppData\Local\Microsoft\WindowsApps;D:\ware\Java\jdk1.8\bin;D:\ware\Java\jdk1.8\jre\bin;D:\ware\scala11\bin;D:\ware\scala11\jre\bin;D:\ware\apache-maven\bin;D:\ware\ffmpeg\bin;D:\ware\hadoop-2.6.4\bin;D:\ware\Microsoft VS Code\bin;C:\Users\me\AppData\Local\BypassRuntm;D:\ware\JetBrains\IntelliJ IDEA 2019.2.1\bin;C:\Users\me\AppData\Roaming\npm;D:\ware\cmder;D:\ware\mysql-8\bin;C:\Users\me\go\bin;C:\Users\me\AppData\Local\Microsoft\WindowsApps;D:\ware\gradle\bin
8 verbose lifecycle mobx-ts-example@1.0.0~pre-build: CWD: E:\me\github\kafka-manager\console
9 silly lifecycle mobx-ts-example@1.0.0~pre-build: Args: [ '/d /s /c', 'cross-env NODE_ENV=production webpack' ]
10 silly lifecycle mobx-ts-example@1.0.0~pre-build: Returned: code: 2  signal: null
11 info lifecycle mobx-ts-example@1.0.0~pre-build: Failed to exec pre-build script
12 verbose stack Error: mobx-ts-example@1.0.0 pre-build: `cross-env NODE_ENV=production webpack`
12 verbose stack Exit status 2
12 verbose stack     at EventEmitter.<anonymous> (D:\ware\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
12 verbose stack     at EventEmitter.emit (events.js:198:13)
12 verbose stack     at ChildProcess.<anonymous> (D:\ware\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:198:13)
12 verbose stack     at maybeClose (internal/child_process.js:982:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid mobx-ts-example@1.0.0
14 verbose cwd E:\me\github\kafka-manager\console
15 verbose Windows_NT 10.0.19041
16 verbose argv "D:\\ware\\nodejs\\node.exe" "D:\\ware\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "pre-build"
17 verbose node v10.16.3
18 verbose npm  v6.9.0
19 error code ELIFECYCLE
20 error errno 2
21 error mobx-ts-example@1.0.0 pre-build: `cross-env NODE_ENV=production webpack`
21 error Exit status 2
22 error Failed at the mobx-ts-example@1.0.0 pre-build script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 2, true ]

**Comment by ZQKC** [comment]
新版再试一下，看是否有该问题

**Comment by ZQKC** [comment]
长期未反馈，是否还存在未知，关闭issure
