### ISSUE TITLE
集群已有的topic接入kafka-manager后无法编辑

### ISSUE THREAD

**Issue by pierre94** [didi/kafka-manager#64]
如图
![image](https://user-images.githubusercontent.com/12579749/94560462-4c64f700-0295-11eb-95c9-c98f24eee7d2.png)
集群已有的topic，应用的信息是不能编辑的，但确认的话又提示为空

![image](https://user-images.githubusercontent.com/12579749/94560509-5be44000-0295-11eb-9fbe-f43a0e6e29f7.png)

**Comment by ZQKC** [comment]
应该是已修复了
