### ISSUE TITLE
无权限

### ISSUE THREAD

**Issue by xueanguo** [didi/kafka-manager#69]
![E89078A2-0D8D-4742-A7A8-F9AFA240F2AF](https://user-images.githubusercontent.com/20197996/96973395-69b27b80-154a-11eb-833b-4b7a77893f6f.png)
修改密码没有权限
版本1.1.0
![10CBCFCC-D65C-477B-8500-F89C56216A82](https://user-images.githubusercontent.com/20197996/96973728-de85b580-154a-11eb-9e4c-a0cd6b2f98f2.png)

**Comment by ZQKC** [comment]
1.1版本问题比较多，欢迎使用2.x版本，旧版本暂时不考虑进行维护了
