### ISSUE TITLE
user_cn_guide.md文档对应的一些链接报404

### ISSUE THREAD

**Issue by huangzhenyou** [didi/kafka-manager#74]
kafka-manager使用手册-待更新里的链接有许多报404.
如图：
![图片](https://user-images.githubusercontent.com/24889436/97957959-30e69200-1de7-11eb-8b3e-8d98a2ecb0c9.png)

![图片](https://user-images.githubusercontent.com/24889436/97957970-37750980-1de7-11eb-923e-6345134ace2a.png)

**Comment by ZQKC** [comment]
使用手册暂未更新上去，我尽快更新一下
